server:
  port: 8080

spring:
  application:
    name: courses-backend
  datasource:
    url: jdbc:mysql://localhost:3306/courses_react?
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true